### ISSUE TITLE
Best practice question

### ISSUE THREAD

**Issue by djomen** [leekelleher/umbraco-ditto#113]
What would you say was best practice for Ditto in relation to the models? To use inheritance to match the document types or to have each doctype as a single POCO and have properties for the other POCOS. For example DType.SEO.MetaDescription

I have done a biggish project before with the PublishedContentModel and used inheritance and you had to keep your inheritance structure this in sync with the DocTypes - but was more efficient dev wise not having to bash out all the properties on each POCO but just the new ones that weren't inherited.

What would you recommend? Is there any performance advantage over each option?

**Comment by mattbrailsford** [comment]
Hey Damian,

This isn't really for us to say from a Ditto perspective as the aim of Ditto is just to be a simple mapper and not enforce any workflow. That said, right now I'm working on something called DitFlo if you fancy taking a look at that which is my attempt at a minimal workflow for those that want to do strongly typing in a simple and flexible manor.

Nip on over to https://github.com/mattbrailsford/umbraco-ditflo and pull / run the demo in the web folder and have a poke around. If you have any questions on it, feel free to post them on the ditflo issue tracker.

I'll leave this issue open for a little while just incase anyone else has any suggestions

**Comment by JimBobSquarePants** [comment]
>This isn't really for us to say from a Ditto perspective as the aim of Ditto is just to be a simple mapper and not enforce any workflow. 

I couldn't agree more. Matt and I work in different ways using Ditto but both achieve great results. 

Coding against a CMS is tricky. Multiple objects can be so similar yet subtly different that classical 
inheritance based on abstract base classes can quickly become convoluted. Since C# cannot perform multiple inheritance I use interfaces to define the functionality and repeatedly implementing them within the individual document type classes. Sure it's not perfectly DRY but it's a LOT easier to follow the code and the classes are only using properties anyway.

I also declare almost every property as virtual. Anything referencing other `IPublishedContent` instances are always declared as such. This allows me to use Ditto's proxy generating feature to lazily load each property on demand. That greatly cuts the overhead of hydrating the classes from the `IPublishedContent` instances.

**Comment by djomen** [comment]
Thats the sort of info I was after - cheers guys! :) Know what you mean about the convoluted process - just wondered if there were any other benefits to the various ways.

I guess there is also the 3rd way of treating an inherited property as if it was on that type so rather than model.SEO.Title you could just have model.Title. Would still work and reduces nesting and therefore makes views simpler.

Will have a good experiment with Ditto and see what i find.

Matt - i checked out you Ditflo repo but got an error with the referenced types on running it - but not had chance to have a poke and see what was wrong. Will have a further play with it when i get time. Thanks.

**Comment by jamiepollock** [comment]
@djomen I'm giving it a try with Umbraco 7.3 RC. Had to make a few modifications to the original project mind.

I need to get my head around how it works. Anything I'd want to discuss would be over on @mattbrailsford's repo though.

Our new project is an attempt at using ditto, ditflo & nested content.l together for the first time.

**Comment by leekelleher** [comment]
Thanks everyone, all good advice.

Feel free to use the [Our Umbraco forum](https://our.umbraco.org/projects/developer-tools/ditto/ditto-feedback/) if you wish to discuss further.
