### ISSUE TITLE
Performance.

### ISSUE THREAD

**Issue by JimBobSquarePants** [leekelleher/umbraco-ditto#140]
I've opened this up purely for the means of discussion as I'm a little worried about Ditto's performance on Azure and I wanted to see if you guys have had any issues at all.

We've recently launched two websites on the Azure platform with the front end powered by Ditto -The performance has been terrible 2+ secs for TTFB without caching. There's nothing too fancy going on, a few inherited classes and some traversal helpers and the back office is as nippy as ever.

It's difficult to tell exactly what is going on. I can't get Miniprofiler to work (too much recursion) but my hunch is that the amount of reflection going on in Ditto is slowing everything down despite our attempts to cache everything.

I'm tempted to try and integrate something like [FastReflection](https://github.com/darrenkopp/FastReflection) to see if that speeds anything up but I wouldn't want to attempt that unless it is truly necessary. 

What are your thoughts/advice?

**Comment by leekelleher** [comment]
We've been using Ditto on UaaS since day one.

I'm not sure if UaaS is configured differently from regular Azure sites?

The initial (uncached) page load does take a while (few seconds). But I was never sure if that was Umbraco or Ditto, (or even UaaS).

I know early on that there was an issue with querying  Examine indexes, since they were on the filesystem, but HQ did something to fix that. (Remember that Core queries Examine for media nodes)

I'll give it more thought and feedback on here.

**Comment by JimBobSquarePants** [comment]
Thanks.... I'll also see if I can run some profiling and tests to see if it is a bottle neck.

**Comment by JimBobSquarePants** [comment]
Still keen to look at this but am going to wait until after #143 is implemented.

**Comment by mattbrailsford** [comment]
Most of #143 is done now. The only thing Lee and I were discussing is
making it backwards compatible by bringing value resolvers / type
converters back, but making them obsolete. These would be done as
processors though, so if we look at performance boosts for processors, I
think that would help for everything (another good reason to make
everything processors :))

**Comment by mattbrailsford** [comment]
Given that expression trees are faster than Activator.CreateInstance, is there any reason the GetInstance method in TypeInitializationExtensions that just accepts a type is:

    public static object GetInstance(this Type type)
    {
        return Activator.CreateInstance(type);
    }

rather than:

    public static object GetInstance(this Type type)
    {
        return GetInstance<TypeToIgnore>(type, null);
    }

I'm assuming you ran tests previously, it's just I'm seeing people say expressions are quicker, so just wondering why we wouldn't use them in all situations?

**Comment by JimBobSquarePants** [comment]
Good question....

Expression trees are much faster for everything other than `Activator.CreateInstance(type)` with a parameterless constructor. That scenario has been carefully optimized by the .Net team and is 2X faster.

The original [blog](http://geekswithblogs.net/mrsteve/archive/2012/02/19/a-fast-c-sharp-extension-method-using-expression-trees-create-instance-from-type-again.aspx) I adapted the code from (You'll have to remove `div.post` css to read it now weirdly) noted this but doesn't implement it in the code. I confirmed his performance results in Linqpad.

![getinstance performance](https://cloud.githubusercontent.com/assets/385879/11701177/24448064-9f22-11e5-9968-26ff07b33b40.gif)

**Comment by mattbrailsford** [comment]
Ooh interesting. Didn't know that :)

**Comment by JimBobSquarePants** [comment]
Perf is my jam :smile:

**Comment by leekelleher** [comment]
Closing this one off for now.  I'd still love a way to benchmark Ditto's performance, but I'm unsure on how to do this. Any attempts that we've tried on local machines or Azure have been inconclusive.
