### ISSUE TITLE
Processors - legacy ValueResolver support?

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#149]
Briefly discussed with @mattbrailsford about the idea of have a "legacy ValueResolver" processor, so that Ditto could maintain some backwards-compatibility.

The main reason for this is to not completely upset Ditto's existing developer-base with a major breaking-change per (minor) release, _even though we are still haven't reached a v1.0 stable release yet._

**Comment by JimBobSquarePants** [comment]
How much additional code/complexity would that require to include vs changes required by the developer?

**Comment by mattbrailsford** [comment]
the changes for devs aren't difficult, it's basically changing the structure to be a processor rather than a value resolver / type converter. You shouldn't need to redo the logic, just update the surrounding class structure.

The thoughts I had on VR/TCs was to make a processor for each of these and add them to the list of processors that run at the end of a conversion request. Code wise it'd be a case of pulling out the same code from the previous version and converting it to a processor. It's likely to run a little slower mind as you'd be creating a processor + context, then creating a resolver + context inside it, then running the VR, but if we mark them obsolete, people should know to upgrade.

Given our flat namespace structure, it shouldn't be too hard to create a legacy folder, and just move all the obsolete stuff to that folder for deleting later. Like Lee says though, I guess it's a question of if we want to bother adding the bloat in, or just say "hey, it's alpha baby!" :)

**Comment by sniffdk** [comment]
Been following on the sideline, just my 2 cents, it's alpha, don't add bloat already :smiley:

**Comment by leekelleher** [comment]
My personal reason for this is that with the 0.8.0 release, I had to change a boat load of `EventHandlers` code to `DittoConversionHandler` ... it wasn't pretty work, and I knew it was coming! :smiling_imp: 

I only had one developer complain to me about that breaking-change at a local meetup. Still, my thinking is that if there's anything we can do to help forewarn and migrate devs over to using Processors, that's worth a discussion. :100:

**Comment by mattbrailsford** [comment]
If we expose a method of modifying the default list processors that run on all requests, in theory, you could probably make a legacy DLL thus keeping it all separate and easy to remove the bloat (in theory).

**Comment by leekelleher** [comment]
Re: "Legacy DLL" - we could probably do this in the [labs repo](https://github.com/leekelleher/umbraco-ditto-labs). (Just thinking out loud)

**Comment by JimBobSquarePants** [comment]
Warn, blog, and document the crap out of it then scrap the old stuff. Most of the translation looks like it should be a fairly simple transition. 

It's pre release and developers should be able to handle that with the appropriate docs.

**Comment by leekelleher** [comment]
Decisions, decisions... OK, let's keep Ditto core codebase lean! :metal:

**Comment by sniffdk** [comment]
rock on :metal: :smile:

**Comment by JimBobSquarePants** [comment]
:metal:
