### ISSUE TITLE
UmbracoPicker returns wrong IPublishedContent in Umbraco 7.5.3

### ISSUE THREAD

**Issue by robertjf** [leekelleher/umbraco-ditto#194]
Hey,
I've just upgraded a project to Umbraco 7.5.3 and Ditto 10.0 (from 8.3), and am seeing some rather odd behaviour.

For example:

Report (id: 1050) has the following:

    public class Report : PublishedContentModel
    {
        public Report(IPublishedContent content) : base(content) { }
        #region Report Content
        private IEnumerable<Section> sections = null;
        public IEnumerable<Section> Sections
        {
            get
            {
                if (sections == null)
                    sections = Children.Where(c => c.DocumentTypeAlias == "Section").As<Section>();

                return sections;
            }
        }

        // Report Front Cover - a Content Node from a Content Picker
        [UmbracoPicker]
        public virtual IPublishedContent FrontCover
        {
            get; set;
        }
    
        // Logo - from a Media Picker
        [UmbracoPicker]
        public virtual IPublishedContent Logo { get; set; }
    
    }

when I render this out and inspect the properties I get:

    report.Id == 1050;
    report.Logo.Id == 1050; (should be 1032)
    report.FrontCover.Id == 1050; (you get the idea)

**Comment by leekelleher** [comment]
@robertjf The issue is that since the processors are chained, if you're using `UmbracoPicker`, you'd need to also add `UmbracoProperty`, so that the processor knows to work with the picked value.

I know it's a bit misleading, since if there are no attributes on a property, then we automagically imply that `UmbracoProperty` will be used.

**Comment by robertjf** [comment]
Aha - thanks, will try that in a little while.  I was wondering about that; but what I don't get is why is the "parent" `IPublishedContent` returned by default?  Why would the Report node be returned instead of trying to use the actual property value?

I couldn't find anything in the documentation around this "feature" - all it suggests is that you replace the `TypeValueConverter` with `UmbracoPicker`.

To me this seems like a bit of an anti-pattern.

**Comment by leekelleher** [comment]
It's not getting the "parent" `IPublishedContent`, it's using the "current" content node, (where else would Ditto/`UmbracoProperty` get the property value from?)

I'm not really sure I follow your anti-pattern remark :-(

If a processor attribute isn't specified then Ditto will assume the default processor (`UmbracoProperty`), if you want other processors, then they'll need to be chained. The alternative is to add `UmbracoProperty` to every POCO property, which was sneered at when we first suggested it.

**Comment by mattbrailsford** [comment]
The reason for not implying UmbracoProperty attribute once you've manually declared a Processor attribute is because you may have no intentions of using the current properties value at all so there is no point running the UmbracoProperty processor. 

Take for example the AppSettingProcessor where you get a value from the web.config. There would be no reason, and thus a waste of processing, for UmbracoProperty to be run beforehand, therefor our rule is, if you declare no attributes, we assume you want to map an umbraco property, but if you declare an attribute, we assume you take full responsibility of the processor chain and this must declare all processors you wish to use.

If you find yourself declaring the same attribute groups constantly, then you can declare a DittoMultiProcessor to encapsulate this.

Hope this helps clarify :)

**Comment by robertjf** [comment]
Wanted to reply to this earlier but suffering from a deficit in the time bank...

I understand the rationale etc. but there's literally no documentation on this feature - I wasn't expecting to have to decorate with two attributes where previously one was enough and the upgrade guide simply says "replace x with y".

I still don't fully understand why the property would return the `IContentPublished` object that's been wrapped by the Model instead of the content represented by the property value - it seems a little counter intuitive to me.

Surely it should be able to detect that the value is an `int` and the property is returning an `IPublishedContent`, then pair that with the use of the `UmbracoPickerAttribute` to return the correct object; or at the very least throw an exception that explains the need for the extra Attribute?

**Comment by mattbrailsford** [comment]
Hi @robertjf ,

We know we have a "lack of documentation" issue and it is on our todo list, but there are only so many hours in the day and our time is so thinly spread with all our packages that unfortunately we haven't gotten around to it yet.

The reason you get the current content being mapped is because from Ditto's perspective, everything happens from the context of "This is the current content, now map me or some element of me to this property". If you have an umbraco property attribute defined on your property, you fall into the "some element of me" part of that statement, but if you have no umbraco property attribute defined, then you fall in the "map me" part of the statement and so you get the current content item being mapped, rather than the property value.

As I say, if you want the property value, you need to declare the UmbracoProperty attribute.

The reason we can't have the UmbracoPickerAtrtibute throw an exception is because we design them to be chainable so they simply check the value and if they can't handle it, or it appears to be in the correct output type for the property (which the IPublishedContent of the current node would be a valid output value for UmbracoPickerAttribute) we simply pass on the value so that other processors can do their thing.

I get your confusion, and I understand we need more documentation on this, but I hope I've explained the logic behind what is happening and what you need to do to get it working.

PS One other option is you can use the core value converters by jeavon then this will make content pickers return IEnumerable<IPublishedContent> by default, meaning you wouldn't need the UmbracoPickerAttribute at all and thus the default UmbracoPropertyAttribute would kick into play.

**Comment by JimBobSquarePants** [comment]
@robertjf One way to handle this is to add an UmbracoPicker attribute to your base classes. They then should automatically work for any classes that inherit them.
