### ISSUE TITLE
Ditto Factory misusing `PluginManager.ResolveTypes`?

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#202]
Something came out of a recent Umbraco support ticket, that our logs were filled with `Umbraco.Core.PluginManager` entries.  Which @Shazwazza raised this question...

> Why is `PluginManager.ResolveTypes` being used so much? The reason your logs are full of this is because it shouldn't be used this way, types should be resolved one time per type in your application, please consider updating your code to only resolve once otherwise you will end up type loading using reflection all of the time and filling up your logs.

It turns out that Ditto Factory is making that call... [`DittoFactoryAttribute.cs` line 45](https://github.com/leekelleher/umbraco-ditto/blob/0.10.0/src/Our.Umbraco.Ditto/ComponentModel/Processors/DittoFactoryAttribute.cs#L45).

I can see why we're calling `ResolveTypes` from within the factory, but wondering if there's a better way to rectify this?

**Comment by leekelleher** [comment]
Oops! I've just noticed the `AllowedTypes` property... which will work around my specific issue.

_Making a note to make this more prominent in our upcoming documentation._

**Comment by JimBobSquarePants** [comment]
That method needs caching and also the result needs caching also. There's examples in the code where I cache reflected methods. 

https://github.com/leekelleher/umbraco-ditto/blob/0.10.0/src/Our.Umbraco.Ditto/Common/CachedInvocations.cs

After that I would use a static ConcurrentDictionary to store the type and the resultant type collection.

**Comment by mattbrailsford** [comment]
I've kept it simple for now and just wrapped it in an ApplicationContext RunttimeCache method. Should do the trick.

**Comment by JimBobSquarePants** [comment]
That's one way to do it! 😄 I'll try and have a look when I'm a little less swamped in this imaging rubbish I keep messing about with.

**Comment by Shazwazza** [comment]
For this type of thing you should just be storing the result on an instance property. If you don't have that then use the StaticCache not RuntimeCache - the RuntimeCache can become cleared and then you have cache turnover problems if you fill it up. Resolving types should exist in memory and never leave, they can and will not ever change during the lifetime of the app domain.

**Comment by mattbrailsford** [comment]
Cheers Shan, will update to static cache.

**Comment by mattbrailsford** [comment]
Switched to static cache in commit c6b8637a88083e2655fdefa161bf1703a85aa0c5

**Comment by mattbrailsford** [comment]
@Shazwazza out of interest, where is StaticCache saved? is there a way to clear this if needed? We used RuntimeCache because I'm under the impression this lasts until the next AppPool recycle which seemed a good fit as it's possible peoples classes change due to a compile. Would be good to know when each should be used.

**Comment by Shazwazza** [comment]
Static cache is saved to a static dictionary. Runtime cache should be used when you want to cache application wide for a period of time but eventually want it to expire, because you know it's either going to become stale or because you know it won't be used any longer and you want to free up some memory. 

Static cache is rare, normally if you want to static cache something you'd use your own variables in your own classes but you have the option to use this too. As with all static variables, there is no expiration. 

Both static cache and runtime cache are cleared on app domain restart. 

Since you are storing your resolved types from the app domain here you would never need to clear it, it will never become stale until the next app domain restart.

**Comment by mattbrailsford** [comment]
Awesome! Thanks for the explanation. Really useful.
