### ISSUE TITLE
RenderModel extension restrictions.

### ISSUE THREAD

**Issue by JimBobSquarePants** [leekelleher/umbraco-ditto#37]
In [RenderModelExtensions.cs](https://github.com/leekelleher/umbraco-ditto/blob/develop/src/Our.Umbraco.Ditto/Extensions/RenderModelExtensions.cs#L35) there is a restriction on the extension method that limits the return type `T` to implementations of `RenderModel`. 

Is that correct? It seems to me too restrictive since we are operating on the `Content` property. I assumed that this method was just a short-cut to `IPublishedContent.As<T>`

**Comment by leekelleher** [comment]
The constraint was put there only because in the initial implementation we required it return a `RenderModel` (well an object that inherited from `RenderModel`).

The original extension had much more going on in it, as it populated some top-level properties, etc.

As you say, now it is essentially a short-cut for `model.Content.As<T>` - I'm wondering what is the point of it too.

Do you use it?

**Comment by leekelleher** [comment]
> Just thinking out loud :-)

Maybe in [PublishedContentExtensions.cs](https://github.com/leekelleher/umbraco-ditto/blob/develop/src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs#L358) we could pass in the `culture` (as an optional param)?

Then from the `RenderModel` extension it could use `model.Culture`?

**Comment by JimBobSquarePants** [comment]
I think it's a nice short-cut for the first line of code if you're not using the factory. I'd opt to keep it just drop the restriction.

Yeah, that seems like a good idea. Culture should be over-writeable, same as `RenderModel`

**Comment by leekelleher** [comment]
Closing ticket, resolved in PR #40
