### ISSUE TITLE
make parameter optional for UmbracoDictionary and AppSetting resolvers

### ISSUE THREAD

**Issue by Hendy** [leekelleher/umbraco-ditto#74]
if a dictionary key, or an app setting key aren't provided with their corresponding attribute, then fall-back to using the property name

**Comment by leekelleher** [comment]
:+1: 

You know the only reason I didn't do this for the Dictionary one is because on my website implementations the dictionary names are dot-namespaces, e.g. "Client.Project.Labels.Name".
So they'd never match up with the POCO property name.  But I can see the usage in this - so yes, totally valid issue!

**Comment by Hendy** [comment]
Hi @leekelleher I should be able to do that later today

**Comment by leekelleher** [comment]
Thanks @Hendy! #h5yr

**Comment by leekelleher** [comment]
Closing issue, as PR opened #75
